#!/bin/zsh

if [ $# -eq 0 ]; then

	# normal 
	tmux split-window -h
	tmux resize-pane -L 40
	tmux select-pane -t 1
	tmux send-keys -t 1 'cd $(pwd) ; vim' C-m

else

	case $1 in 
		1)
			tmux split-window -v
			tmux resize-pane -D 20
			vim
			;;

		2)
			tmux split-window -v 
			tmux resize-pane -D 13 
			tmux send-keys -t 1 'tmux split-window -h' C-m 
			tmux send-keys -t 1 'tmux split-window -h' C-m
			tmux send-keys -t 0 'tmux split-window -h' C-m
			;;


		*)
			echo 'ide: [ERROR] corresponding argument not found '
		

	esac

fi
